# Generated by Django 5.1.3 on 2024-11-11 15:12

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rules', models.CharField(max_length=200)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('client_name', models.CharField(max_length=50)),
                ('sector', models.CharField(choices=[('state_govt', 'State Govt'), ('central_govt', 'Central Govt'), ('private', 'Private')], max_length=20)),
                ('client_gst', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_singed', models.DateField(blank=True, null=True)),
                ('contract_period', models.DateField(blank=True, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('client_address', models.TextField()),
                ('client_city', models.CharField(blank=True, max_length=50, null=True)),
                ('client_pincode', models.CharField(blank=True, max_length=50, null=True)),
                ('lut_tenure', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_type', models.CharField(choices=[('sq_feet', 'Sq Feet'), ('man_power', 'Man Power')], max_length=20)),
                ('shift_type', models.CharField(choices=[('day_shift', 'Day Shift'), ('night_shift', 'Night Shift'), ('round_shift', 'Round Shift')], max_length=20)),
                ('client_logo', models.ImageField(blank=True, default='default_logo.jpg', null=True, upload_to='client_logos')),
                ('active_status', models.BooleanField(default=True)),
                ('designation', models.ManyToManyField(blank=True, related_name='client_designations', to='general.designation')),
                ('service', models.ManyToManyField(blank=True, related_name='client_services', to='general.services')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Client',
            },
        ),
        migrations.CreateModel(
            name='ClientSalarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('salary_type', models.CharField(choices=[('Monthly', 'monthly'), ('Daily', 'daily')], default='monthly', max_length=50)),
                ('epf_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esi_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_choice', models.CharField(choices=[('None', False), ('Percentage', 'percentage'), ('Value', 'value')], default='percentage', max_length=20)),
                ('bonus_value', models.CharField(default=0, max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='clients.client')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_rule', to='clients.rule')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EarningsComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('basic_vda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earnings_components', models.JSONField(blank=True, null=True)),
                ('client_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_earnings', to='clients.clientsalarysettings')),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_salary_components', to='general.designation')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeductionComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('professional_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lwf_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('canteen', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('swf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deduction_components', models.JSONField(blank=True, null=True)),
                ('earnings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='clients.earningscomponent')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
