# Generated by Django 5.1.3 on 2024-11-11 15:12

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('employee_details', models.TextField(blank=True, null=True)),
                ('employee_bank', models.TextField(blank=True, null=True)),
                ('employee_payslips', models.TextField(blank=True, null=True)),
                ('employee_loans', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Deleted Employee',
                'verbose_name_plural': 'Deleted Employee',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('emp_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('phone_no', models.CharField(db_index=True, max_length=15, unique=True)),
                ('whatsappNum', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('bloodGroup', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('uanNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar', models.CharField(max_length=20, unique=True)),
                ('pan_card', models.CharField(blank=True, max_length=30, null=True)),
                ('esiNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateField()),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='user_profile/')),
                ('pcc_image', models.ImageField(blank=True, null=True, upload_to='emp_pcc/')),
                ('aadhar_image', models.ImageField(blank=True, null=True, upload_to='emp_aadhar/')),
                ('bank_passbook', models.ImageField(blank=True, null=True, upload_to='emp_passbook/')),
                ('is_active', models.BooleanField(default=True)),
                ('current_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_company', to='clients.client')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='general.designation')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('year', models.IntegerField(default=2024)),
                ('month', models.CharField(max_length=20)),
                ('attendance', models.TextField()),
                ('night_duty', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance', to='employees.employee')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('accountNumber', models.CharField(max_length=20, unique=True)),
                ('ifscCode', models.CharField(max_length=20)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_bank', to='general.banks')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_bank', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee Bank',
                'verbose_name_plural': 'Employee Bank',
            },
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('last_worked', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_history', to='employees.employee')),
                ('prev_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worked_company', to='clients.client')),
            ],
            options={
                'verbose_name': 'Employee History',
                'verbose_name_plural': 'Employee History',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deduction_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('issued_date', models.DateField()),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_loan', to='employees.employee')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deducted_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid_date', models.DateField(auto_now_add=True)),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_history', to='employees.employeeloan')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('attendance', models.CharField(max_length=20)),
                ('earnings', models.JSONField()),
                ('deductions', models.JSONField()),
                ('total_earnings', models.IntegerField(default=0)),
                ('total_deductions', models.IntegerField(default=0)),
                ('grand_total', models.CharField(max_length=100)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='employees.employee')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_emp', to='employees.employee')),
                ('prev_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_company', to='clients.client')),
                ('shifted_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_company', to='clients.client')),
            ],
            options={
                'verbose_name': 'Shifted Employee',
                'verbose_name_plural': 'Shifted Employee',
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['phone_no', 'aadhar', 'esiNumber'], name='employees_e_phone_n_687ae0_idx'),
        ),
    ]
